name: CICD-TO-AWS
env: 
  EB_PACKAGE_S3_BUCKET_NAME : "adv-it-flask-application-packages"
  EB_APPLICATION_NAME       : "test-dev-app"
  EB_ENVIRONMENT_NAME       : "TestDevApp-env"
  DEPLOY_PACKAGE_NAME       : "flask_app_${{ github.sha }}.zip"
  AWS_REGION_NAME           : "eu-central-1"


on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]


jobs:
  ci_part: 
    runs-on: ubuntu-latest
    
    steps:  
    - name : Git clone our repo
      uses : actions/checkout@v1
    
    - name: Create ZIP deployment package
      run : zip -r ${{ env.DEPLOY_PACKAGE_NAME }} ./ -x *.git*
    
    
