name: CICD-TO-AWS
env: 
  EB_PACKAGE_S3_BUCKET_NAME : "package-s3-backet"
  EB_APPLICATION_NAME       : "test-dev-app"
  EB_ENVIRONMENT_NAME       : "TestDevApp-env"
  DEPLOY_PACKAGE_NAME       : "flask_app_${{ github.sha }}.zip"
  AWS_REGION_NAME           : "eu-central-1"


on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]


jobs:
  ci_part: 
    runs-on: ubuntu-latest
    
    steps:  
    - name : Git clone our repo
      uses : actions/checkout@v1
    
    - name: Create ZIP deployment package
      run : zip -r ${{ env.DEPLOY_PACKAGE_NAME }} ./ -x *.git*
    
    - name: Configure my AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id    :  ${{ secrets.AWS_ACCESS_KEY }}
        aws-secret-access-key:  ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region           :  ${{ env.AWS_REGION_NAME }} 
    
    - name: Copy Deployment package to S3 bucket
      run : aws s3 cp ${{ env.DEPLOY_PACKAGE_NAME }}  s3://${{ env.EB_PACKAGE_S3_BUCKET_NAME }}/
    
    - name: Message for CI finish
      run : echo "CI Pipeline part Finished successfully!"
